### PR TITLE
Need \n for Printing untagged message

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes 
https://github.com/projectatomic/buildah/issues/133#issuecomment-311847186

**Comment by rhatdan** [comment]
@14rcole PTAL

**Comment by 14rcole** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+  	4a85aaf

**Pull request closed without merging**
