### PR TITLE
Don't build btrfs if it is not installed

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Does this address #1015?

**Comment by rhatdan** [comment]
Thats the goal
@wking PTAL

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by TomSweeneyRedHat** [comment]
Looks like redhat ci failed with a network hiccup

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by Conan-Kudo** [comment]
😢

**Pull request closed without merging**
