### PR TITLE
Try to enable "run" tests in CI

### PR DESCRIPTION
**Pull request by nalind**
Try to ensure that we have runc, so that we can test the `run` command in CI.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, but I think I'm losing it, thought this had been done already.

**Comment by TomSweeneyRedHat** [comment]
Ugh, gotta stop clicking too quickly today, my emergency mouse isn't as responsive as my normal mouse that I forgot in the office yesterday.  Apologies for the close.

**Comment by nalind** [comment]
@TomSweeneyRedHat no worries.  I just realized that we were skipping most of the tests in `run.bats` because the CI testers didn't have `runc` installed.

**Comment by nalind** [comment]
[(3) [buildah] Run tests that run runc, in CI](https://trello.com/c/WLwEY8IZ/585-3-buildah-run-tests-that-run-runc-in-ci)

**Comment by rhatdan** [comment]
Would we still test on travis to cover ubuntu use cases?

**Comment by nalind** [comment]
Yes.  We need to supply our own `runc`, though, since a packaged, compatible version may not be around.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ https://github.com/projectatomic/buildah/pull/202/commits/cb6ab6428d59c234f4f7dceb5780d87adc3a3f7e
LGTM More testing is good.

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ cb6ab64

**Pull request closed without merging**
