### PR TITLE
Remove --destination flag from `buildah add|copy`

### PR DESCRIPTION
**Pull request by rhatdan**
We need to match the syntax of Dockerfile, three forms

buildah copy $CID SOURCE
buildah copy $CID SOURCE DESTINATION
buildah copy $CID SOURCE SOURCE SOURCE DESTINATION

### CODE REVIEW

**Comment by nalind** [comment]
LGTM.  If we aren't checking that specifying what would be a file as a destination produces an error when we try to copy more than one thing to the container, we should add a test for that.

**Comment by rhatdan** [comment]
Added tests.

**Comment by nalind** [comment]
Merging.

@rh-atomic-bot r+ 37fd317abac0519d2d51a4468bdff12803282d8d

**Comment by nalind** [comment]
[[Buildah] (8) buildah CLI overhaul](https://trello.com/c/LULizZlk/442-buildah-8-buildah-cli-overhaul)

**Pull request closed without merging**
