### PR TITLE
Remove projectatomic/libpod

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by ripcurld** [comment]
@rhatdan it seems like the CI fails due to a problem in `containers/libpod`.

```shell
vendor/github.com/containers/libpod/pkg/secrets/secrets.go:13:2: cannot find package "github.com/projectatomic/libpod/pkg/rootless" in any of:
	/root/gopath/src/github.com/projectatomic/buildah/vendor/github.com/projectatomic/libpod/pkg/rootless (vendor tree)
	/usr/lib/golang/src/github.com/projectatomic/libpod/pkg/rootless (from $GOROOT)
	/root/gopath/src/github.com/projectatomic/libpod/pkg/rootless (from $GOPATH)
```

`libpod/pkg/secrets/secrets.go` depends on `libpod/pkg/rootless` which is removed from `vendor` in this PR.

**Comment by rhatdan** [comment]
Yes I think I have to fix this up in libpod first.

**Comment by TomSweeneyRedHat** [comment]
Change LGTM if you can figure out the libpod change timing.

**Comment by rhatdan** [comment]
Replaced with a different PR>

**Pull request closed without merging**
