### PR TITLE
Dev/tsweeney/docfix/5

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Adding the skopeo-containers package to the list or required packages

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Ugh, will have to do the merge tomorrow.  Need to scat now.

**Comment by nalind** [comment]
The file that contains `/etc/containers/policy.json` might be a different one on other distributions, but it's a reasonable guess.  LGTM.

**Comment by nalind** [comment]
Can we rebase this to avoid including the merge commit?

**Comment by nalind** [comment]
Rebase looks good.  Once CI comes back we're okay to merge.

**Comment by nalind** [comment]
@rh-atomic-bot r+ f36fee20b70c804234121721fd45ffebbcfcf94f

**Pull request closed without merging**
