### PR TITLE
contrib/rpm/buildah_copr.spec

### PR DESCRIPTION
**Pull request by baude**
Tom and I decided we would not edit the original RPM spec
for copr builds and would instead provide a second one.

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
There should be only one spec.  We should drop the old one, if this one is going to be used regularly.  Anyone who wishes to build a package off of the spec should be able to use this one.

**Comment by baude** [comment]
bot, retest this please

**Comment by baude** [comment]
removed the "other" spec file and left just the copr one, renamed it to buildah.spec

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please

**Pull request closed without merging**
