### PR TITLE
Vendor in latest containers/image and containers/storage

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @pixdrift @TomSweeneyRedHat @umohnani8 PTAL

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
Rebaseed and pushed to see if this would clear up testing code.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
