### PR TITLE
buildah-inspect: fix format option

### PR DESCRIPTION
**Pull request by q384566678**
Add a validation and completion code.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM, @rhatdan or @nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
@q384566678 just noticed, can you squash your commits?

**Comment by q384566678** [comment]
Fine, updated.

**Comment by pixdrift** [comment]
CI failure looks unrelated, @TomSweeneyRedHat can you re-run?

**Comment by TomSweeneyRedHat** [comment]
@q384566678 thanks for squashing the comit.  Will see it the bot will retest this for me.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by pixdrift** [comment]
Nice one 👍

**Pull request closed without merging**
