### PR TITLE
Apply Last-Modified time as mtime when saving URLs

### PR DESCRIPTION
**Pull request by nalind**
When saving the contents of a URL to a local file, attempt to set mtime based on the response's Last-Modified header, if there is one.

### CODE REVIEW

**Comment by rhatdan** [comment]
:+1:

**Comment by nalind** [comment]
Telling Travis to run the tests under sudo without resetting $PATH, so the go compiler should be found at test-time.

**Comment by nalind** [comment]
Merging, since the last revision changed the invocation of sudo in the Travis config, and nothing else.
@rh-atomic-bot +r f65c3061e3e28fb3ef1efb749db549744343a27d

**Comment by nalind** [comment]
@rh-atomic-bot r+ f65c3061e3e28fb3ef1efb749db549744343a27d

**Pull request closed without merging**
