### PR TITLE
Use errors.New() instead of Wrapf() for new errors

### PR DESCRIPTION
**Pull request by nalind**
Call `errors.New()` instead of calling `errors.Wrapf()` when there's no error to wrap.

### CODE REVIEW

**Comment by rhatdan** [comment]
Why not go all the way
```
 grep -r fmt.Errorf . | grep -v vendor | grep -v .git
./user_unix_cgo.go:		return nil, fmt.Errorf("%q is not a regular file", ctrfile)
./image.go:		return nil, fmt.Errorf("no supported manifest types (attempted to use %q, only know %q and %q)",
./image.go:				return nil, fmt.Errorf("error storing layer %q to file: inconsistent layer size (copied %d, wrote %d)", layerID, size, counter.Count)
./image.go:	return nil, fmt.Errorf("can't write to a container")
./image.go:	return []byte{}, "", fmt.Errorf("TODO")
./import.go:		return nil, fmt.Errorf("container name must be specified")
./import.go:		return nil, fmt.Errorf("image name must be specified")
./imagebuildah/util.go:		return fmt.Errorf("no contents in %q", url)
./imagebuildah/util.go:	return "", "", fmt.Errorf("unreachable code reached")
./imagebuildah/build.go:		return fmt.Errorf("unable to locate temporary directory for container")
./imagebuildah/build.go:		return fmt.Errorf("error adding %q to the volume cache", path)
./imagebuildah/build.go:		return fmt.Errorf("no build container available")
./imagebuildah/build.go:	return fmt.Errorf("Unrecognized instruction: %#v", step)
./imagebuildah/build.go:		return fmt.Errorf("error building: no dockerfiles specified")
./imagebuildah/build.go:				return fmt.Errorf("no contents in %q", dfile)
./cmd/buildah/umount.go:		return fmt.Errorf("container ID must be specified")
./cmd/buildah/umount.go:		return fmt.Errorf("too many arguments specified")
./cmd/buildah/bud.go:		return fmt.Errorf("unrecognized image type %q", format)
./cmd/buildah/bud.go:		return fmt.Errorf("no context directory specified, and no dockerfile specified")
./cmd/buildah/inspect.go:		return fmt.Errorf("container or image name must be specified")
./cmd/buildah/inspect.go:		return fmt.Errorf("too many arguments specified")
./cmd/buildah/inspect.go:		return fmt.Errorf("the only recognized types are %q and %q", inspectTypeContainer, inspectTypeImage)
./cmd/buildah/common.go:		return nil, fmt.Errorf("error finding build container")
./cmd/buildah/common.go:		return nil, fmt.Errorf("error mocking up build configuration")
./cmd/buildah/commit.go:		return fmt.Errorf("container ID must be specified")
./cmd/buildah/commit.go:		return fmt.Errorf("an image name must be specified")
./cmd/buildah/commit.go:		return fmt.Errorf("too many arguments specified")
./cmd/buildah/commit.go:		return fmt.Errorf("unrecognized image type %q", format)
./cmd/buildah/mount.go:		return fmt.Errorf("too many arguments specified")
./cmd/buildah/run.go:		return fmt.Errorf("container ID must be specified")
./cmd/buildah/rm.go:		return fmt.Errorf("container ID must be specified")
./cmd/buildah/from.go:		return fmt.Errorf("an image name (or \"scratch\") must be specified")
./cmd/buildah/from.go:		return fmt.Errorf("too many arguments specified")
./cmd/buildah/addcopy.go:		return fmt.Errorf("container ID must be specified")
./cmd/buildah/tag.go:		return fmt.Errorf("image name and at least one new name must be specified")
./cmd/buildah/rmi.go:		return fmt.Errorf("image name or ID must be specified")
./cmd/buildah/config.go:		return fmt.Errorf("container ID must be specified")
./cmd/buildah/config.go:		return fmt.Errorf("too many arguments specified")
Binary file ./buildah matches
./buildah.go:		return nil, fmt.Errorf("container is not a %s container", Package)
./add.go:		return fmt.Errorf("error reading contents for %q: wrong length (%d != %d)", destination, n, resp.ContentLength)
./add.go:		return fmt.Errorf("%q already exists, but is not a subdirectory)", filepath.Dir(dest))
./add.go:		return fmt.Errorf("destination %q is not a directory", dest)
./config.go:		return docker.V2Image{}, fmt.Errorf("error parsing image configuration from manifest")
./config.go:		return docker.V2Image{}, fmt.Errorf("error parsing image configuration from history")
```

**Comment by nalind** [comment]
Well, my goal was to fix compile errors, but yeah, why not.  Updated.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 535e433

**Pull request closed without merging**
