### PR TITLE
Name is specified as an argument.

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
I find the handling of --root and --link to be confusing here?  When would I specify these?  
Wouldn't I just use

buildah mount ID /mnt

And then be able to put my content into /mnt?

**Comment by nalind** [comment]
The implementation of some of the storage drivers requires that only the drivers themselves decide where a layer gets mounted, so in the example above, `/mnt` could never be the layer's main mount point.  Adding a symbolic link from a specified location that points to the root directory of a container's read-write layer is an affordance, but given that we return the location when `mount` succeeds, I wouldn't mind if we stopped.  Alternately, we could rip symlinks out and replace them with bind mounts.

**Comment by rhatdan** [comment]
I am looking for the most obvious command to the user which I think is 

buildah mount SRC DEST

**Comment by rhatdan** [comment]
@nalind This now passes tests and requires that the name/id is always passed.

**Comment by rhatdan** [comment]
Closed via https://github.com/projectatomic/buildah/pull/27

**Pull request closed without merging**
