### PR TITLE
Run(): don't use a callback when a slice will do

### PR DESCRIPTION
**Pull request by nalind**
`moreCreateArgs()` doesn't need to be a function; it can just be a slice.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@umohnani8 @TomSweeneyRedHat @giuseppe PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, but thought I'd done so a while ago....

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by giuseppe** [comment]
LGTM

**Pull request closed without merging**
