### PR TITLE
Fix wrong order of parameters

### PR DESCRIPTION
**Pull request by SHooZ**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
@SHooZ thanks a bunch for the PR.  Before we can accept it, you need to sign it via "git commit --amend -s" and then repushing the patch.  The change itself LGTM, so thanks!

**Comment by SHooZ** [comment]
@TomSweeneyRedHat done

**Comment by rhatdan** [comment]
LGTM
@SHooZ  THanks.
@rh-atomic-bot r+

**Pull request closed without merging**
