### PR TITLE
vendor: update containers/storage

### PR DESCRIPTION
**Pull request by giuseppe**
Update to version 58f557cf12df3e11437485f329c15b5c20bebb90

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@TomSweeneyRedHat this changes only containers/storage not containers/image.  I am wondering more about: https://github.com/containers/storage/pull/137 that I'd like to include as well in our tools :smile:

**Comment by TomSweeneyRedHat** [comment]
DOH!  You're right, I must be having too much July 4th fun.  A straight LGTM then.

**Comment by giuseppe** [comment]
@rhatdan done :arrow_up:

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@giuseppe Could you write up a couple of blogs on why these versions of container/storage are important and useful.

**Comment by giuseppe** [comment]
yes, I'll do that.  In the last days I've done a lot of improvements in https://github.com/giuseppe/containerfs and solved all the design issues I didn't like.  I think it is in a good shape for a tech preview.

**Pull request closed without merging**
