### PR TITLE
Switch to sysregistriesv2

### PR DESCRIPTION
**Pull request by nalind**
Switch from using `github.com/containers/image/pkg/sysregistries` to using `github.com/containers/image/pkg/sysregistriesv2` to complete unqualified image names.  Keep v1 around because it'll tell us which configuration file to name in an error message if things don't work right.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
FYI @vrothberg (not sure if you watch Buildah).

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by nalind** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
