### PR TITLE
Need to block access to kernel files systems in /proc and /sys

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Same questions as from https://github.com/projectatomic/libpod/pull/61/files, if that's all hip, then LGTM.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Comment by rhatdan** [comment]
Yes if they are missing it is ok.  We should ask about the sysrq one on CRI-O or in docker, if it is also readonly there?

**Pull request closed without merging**
