### PR TITLE
Vendor in lates containers/image

### PR DESCRIPTION
**Pull request by rhatdan**
Should fix image handling of older format images

### CODE REVIEW

**Comment by rhatdan** [comment]
Hopefully fixes https://github.com/projectatomic/buildah/issues/684

**Comment by rhatdan** [comment]
@mtrmac @umohnani8 @pixdrift @nalind @TomSweeneyRedHat @ripcurld PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by mtrmac** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=pixdrift

**Pull request closed without merging**
