### PR TITLE
Update urvave/CLI and add handling of short options.

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Fixes https://github.com/projectatomic/buildah/issues/895

**Comment by vrothberg** [comment]
LGTM

I hope the upstream patch gets merged soon.

**Comment by rhatdan** [comment]
Me too, nice work waking them up.

**Comment by TomSweeneyRedHat** [comment]
LGTM
But your title got me overly excited.  I was thinking @vrothberg's patch had been merged upstream finally.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by vrothberg** [comment]
Tests are passing now. Travis had some serious hiccups.

@rh-atomic-bot r=TomSweeneyRedHat

**Pull request closed without merging**
