### PR TITLE
Bump to version 0.11

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
Change LGTM, but Red Hat CI doesn't seem happy with  buildah-containers.md for some reason again.

**Comment by nalind** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=@ripcurld0

**Comment by rhatdan** [comment]
Packages available in Fedora 
https://bodhi.fedoraproject.org/updates/FEDORA-2018-e821bfc2b2
Please test and update karma, if you have the time.

**Comment by rhatdan** [comment]
@ripcurld0 ^^

**Comment by ripcurld0** [comment]
Hi @rhatdan I would love that.
Any particular document that I should read before testing it or should I be creative?
In addition, how do I update karma?

Thanks.

**Comment by rhatdan** [comment]
@ripcurld0 Just do general testing, whatever you want to do, as long as it works as well as previous version, is really what we want to make sure.

Updating Karma.
If you have a fedora account, you can login and go to the link above.  After testing, put a comment in here that everything works as designed.  When your comment goes through the karma will increase.  As soon as 3 people say it works for them, it will get pushed into release.

**Comment by ripcurld0** [comment]
Seems like we have a small problem with `/usr/share/bash-completion/completions/buildah`. It says it is supposed to be executable. I am not sure that's true. This is a bash-completion, it doesn't have to be executable. Am I wrong?

Sure, no problem! I will work on this in the following days 😄

**Comment by rhatdan** [comment]
No it should not need to be executable.

**Comment by ripcurld0** [comment]
`karma++`ed today. LGTM.

**Pull request closed without merging**
