### PR TITLE
Makefile: "clean" should also remove test helpers

### PR DESCRIPTION
**Pull request by nalind**
Make "make clean" also remove the `imgtype` test helper.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Can you update the commit title or message to indicate the lint fix. 

Othewise LGTM and the tests are happy!  I think you nailed it.

**Comment by TomSweeneyRedHat** [comment]
hmm, wait a minute, I actually see two commits under one github location.   Looks like you've a good commit message for the addon, nvm.  (But would like to know how/what you did in git to make that happen).

**Comment by nalind** [comment]
Opened #221 to just get the `--enable-gc` flag in.  This PR was itself split off from one that it wasn't directly related to, so it makes more sense to me to have this go back to being just one patch once we merge that one.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ ba6116d

**Comment by nalind** [comment]
@rh-atomic-bot retest

**Comment by rhatdan** [comment]
@rh-atomic-bot r+  e1df30f

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 98c4e0d

**Comment by rhatdan** [comment]
@rh-atomic-bot r=rhatdan 98c4e0d

**Pull request closed without merging**
