### PR TITLE
userns: assign additional IDs sequentially

### PR DESCRIPTION
**Pull request by giuseppe**
currently, when I am running buildah as unprivileged user, I get this
mapping in the container, thus having unmapped ids [1-first additional
id]:

          0         1000              1
110000     110000      65536

change the mapping so that now looks like:

0       1000          1
1     110000      65536

Closes: https://github.com/projectatomic/buildah/issues/882

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@nalind PTAL

**Comment by nalind** [comment]
LGTM once it passes CI.

**Comment by rhatdan** [comment]
@giuseppe Lint does not like Uid, it wants UID variables.

**Comment by TomSweeneyRedHat** [comment]
I'd problems testing @rhatdan 's #883 this morning so started a new VM and restested.  With those bits in place, #882 seems to be working fine now.  However if I add this PR to those bits I'm getting the below Error.  :^(

```
STEP 3: COMMIT containers-storage:[vfs@/home/tom/.local/share/containers/storage+/run/user/1000/run]localhost/myimg:latest
Getting image source signatures
Skipping fetch of repeat blob sha256:891e1e4ef82ad02a4ea1f030831f942d722c7694c4db64ca3239c8163b811c58
Copying blob sha256:045459c45d8f01b3a9d6425a893ea87ce18957d0b92db641edb7b525a2806816
 198.98 MiB / 198.98 MiB [==================================================] 5s
Copying config sha256:9f78bc55a9294b43770dcb4435439a6e3df19c102983fa94861a4ac3f3c45a9c
 1.56 KiB / 1.56 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
ERRO[0165] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: lchown /etc: invalid argument 
error copying layers and metadata: Error committing the finished image: error adding layer with blob "sha256:045459c45d8f01b3a9d6425a893ea87ce18957d0b92db641edb7b525a2806816": ApplyLayer exit status 1 stdout:  stderr: lchown /etc: invalid argument
ERRO[0166] exit status 1                             
```

**Comment by giuseppe** [comment]
@TomSweeneyRedHat how are you testing it?  I've tried, based on #882:

```console
$ cat /tmp/foo/Dockerfile 
FROM fedora:28
RUN dnf -y update

$ buildah bud --net host -t myimg  /tmp/foo
[...lot of output...]
Complete!
STEP 3: COMMIT containers-storage:[vfs@/home/gscrivano/.local/share/containers/storage+/run/user/1000/run]localhost/myimg:latest
Getting image source signatures
Skipping fetch of repeat blob sha256:891e1e4ef82ad02a4ea1f030831f942d722c7694c4db64ca3239c8163b811c58
Copying blob sha256:e3222f9db55256360c1fa3ce24c23e56a5eeaa7c65d80a885f4e80ce70970282
 198.99 MiB / 198.99 MiB [==================================================] 6s
Copying config sha256:b01595ed66f65fb7d7dde74cadeca0f4fdf749f258d681013351d069307b652b
 1.56 KiB / 1.56 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
--> b01595ed66f65fb7d7dde74cadeca0f4fdf749f258d681013351d069307b652b
```

**Comment by giuseppe** [comment]
Redhat CI is passing, still wating for Travis

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
OK, I think I found the issue, not completely sure how I got there though.   This morning I installed a fresh VM and installed the latest bits including @giuseppe's.  The test ran without an issue.  So I went back to the old VM and reinstalled from scratch.  Still the same error.  I tried removing the /var/lib/containers/storage directory, but no change there, then I remembered the non-priv path wrote to ~/.local/containers/storage.  After removing that and then retrying, things worked fine.

So I'm going to assume that on my old VM I first installed problematic code that @giuseppe then fixed, however, I didn't clean out ~/.local as I should have after reinstalling and retesting the good code.

**Pull request closed without merging**
