### PR TITLE
Use the right formatting when adding entries to /etc/hosts

### PR DESCRIPTION
**Pull request by nalind**
Append address+"\t"+hostname to the hosts file instead of the "hostname:address" format that we picked up from the command line.

### CODE REVIEW

**Comment by nalind** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
@nalind, looks like some of the go tests aren't happy.

```
=== RUN   TestAddHosts
--- FAIL: TestAddHosts (0.00s)
	run_test.go:108: expected test "host list" to not receive error: unable to parse host entry "localhost": incorrect format
	run_test.go:112: test "host list" failed: expected buffer to have "localhost\nhost-1\nhost-2\n" but got ""
=== RUN   TestAddHostsToFile
--- FAIL: TestAddHostsToFile (0.00s)
	run_test.go:169: failed to add hosts to file: unable to parse host entry "host-1": incorrect format
	run_test.go:177: test "empty hosts file" failed: expected content to be "host-1\nsystem-1\n" but got ""
	run_test.go:169: failed to add hosts to file: unable to parse host entry "host-0": incorrect format
	run_test.go:177: test "append hosts to file" failed: expected content to be "localhost\nhost-0\nhost-1\ndns.name.1\n" but got "localhost\n"
```

**Comment by nalind** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
LGTM
Although tests are failing.

**Comment by rhatdan** [comment]
@umohnani8 @TomSweeneyRedHat @pixdrift @giuseppe PTAL

**Comment by umohnani8** [comment]
LGTM

**Pull request closed without merging**
