### PR TITLE
Vendor in latest selinux-go code

### PR DESCRIPTION
**Pull request by rhatdan**
This should make building on non linux systems easier

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vbatts @TomSweeneyRedHat @umohnani8 @nalind @pixdrift PTAL

**Comment by baude** [comment]
LGTM, please merge

**Comment by umohnani8** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
