### PR TITLE
Give better messages to users when image can not be found

### PR DESCRIPTION
**Pull request by rhatdan**
Had to vendor latest containers/image to get path to /etc/containers/registries.conf

Currently if /etc/containers/registries.conf does not exist, you can not pull images
and the error message tells you bad information.

 buildah from alpine
Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused

With this change

./buildah from alpine
image "alpine" not found in /etc/containers/registries.conf registries: image not known

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @umohnani8 PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
