### PR TITLE
Vendor in latest containers/image

### PR DESCRIPTION
**Pull request by umohnani8**
Adds feature to pull compressed docker-archive files

Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@TomSweeneyRedHat @rhatdan PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green test buttons.

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@umohnani8 Could you give us a use case where this is important?

**Comment by umohnani8** [comment]
@rhatdan Actually I don't think buildah pulls images saved to docker-archive or oci-archive. It would be cool to add this though so we can do "buildah from docker-archive:alp.tar" and it will create a container from the image in alp.tar. And buildah push supports all the various transports.

**Pull request closed without merging**
