### PR TITLE
mount: output it before replacing lastError

### PR DESCRIPTION
**Pull request by q384566678**
The same error was found in [#825 discussion](https://github.com/projectatomic/buildah/pull/825#discussion_r198082771). Fix it.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @umohnani8 PTAL

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
Homu does not like us.  @jlebon Any idea why?

**Comment by rhatdan** [comment]
Manually merging.

**Comment by jlebon** [comment]
Looks like the tests are failing:

```
run.go:848::warning: cyclomatic complexity 41 of function (*Builder).Run() is high (> 40) (gocyclo)
make: *** [Makefile:51: validate] Error 1
```

**Pull request merged**
