### PR TITLE
Fix md2man issues

### PR DESCRIPTION
**Pull request by umohnani8**
Signed-off-by: umohnani8 <umohnani@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I have opened an issue with upstream go-md2man package
https://github.com/cpuguy83/go-md2man/issues/34
It looks like it does not like the way we are doing tables.

**Comment by rhatdan** [comment]
This is fine for now, but I would like to revert these once this bug gets fixed.

**Comment by umohnani8** [comment]
@rhatdan Okay, I will open an issue to keep track of this.
Can we get this in for now, so we can test other PRs?

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
