### PR TITLE
Fix a copy/paste error in a man page

### PR DESCRIPTION
**Pull request by nalind**
Well, I think we can all tell what I used as a template when writing the "inspect" man page.

### CODE REVIEW

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 7623c51

**Comment by nalind** [comment]
@rh-atomic-bot retry

**Comment by nalind** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 7623c51

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@jlebon PTAL

**Comment by jlebon** [comment]
@rh-atomic-bot r-

**Comment by jlebon** [comment]
@rh-atomic-bot r+ 7623c51

**Comment by jlebon** [comment]
The reason is that this commit was already merged into master: https://github.com/projectatomic/buildah/commit/9bcd86d87b17e0c9cd47589934bc6d4d077d509b, which confuses the bot. Looks like we can close this one?

**Comment by jlebon** [comment]
(Though we should probably provide a better error message for this).

**Comment by nalind** [comment]
That's weird.  I could've sworn that it hadn't been merged.  Thanks for running it down!  Closing.

**Pull request closed without merging**
