### PR TITLE
Remove chrootuser handling and use libpod/pkg

### PR DESCRIPTION
**Pull request by rhatdan**
I have made a subpackage of libpod to handle chrootuser,
using the user code from buildah.

This patch removes user handling from buildah and uses
projectatomic/libpod/pkg/chrootuser

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by nalind** [comment]
There seems to be an extra copy of conmon in the vendored tree.  Otherwise LGTM.

**Comment by rhatdan** [comment]
I am working to remove conmon from libpod altogether.  vndr pulled in these for some reason.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=nalind

**Pull request closed without merging**
