### PR TITLE
Let util.ResolveName() return parsing errors

### PR DESCRIPTION
**Pull request by nalind**
Allow util.ResolveName() to return errors from libraries that it uses.

### CODE REVIEW

**Comment by nalind** [comment]
I think this'll fix the problem @hettipeti was seeing in #468.

**Comment by nalind** [comment]
The [Fedora Container Registry](https://status.fedoraproject.org/) is currently undergoing planned maintenance, so our tests that expect to reach it are failing.

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
