### PR TITLE
Switch buildah back to ErrorLevel

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by pixdrift** [comment]
Is there any context around why this was reverted? Did something break?

**Comment by TomSweeneyRedHat** [comment]
One of the new changes listed a lot of crufty warning messages.  I don't recall the exact wording but something like:

WARNING variable is an int and being cast to a double.

type of thing many times over in the output of a buildah command.

**Comment by pixdrift** [comment]
ack and cheers @TomSweeneyRedHat

**Comment by rhatdan** [comment]
Yes we need to do a deeper dive to make sure we drop Warning messages down to Info, that are not that important.

**Pull request closed without merging**
