### PR TITLE
[WIP] Add support for a few missing options from buildah run

### PR DESCRIPTION
**Pull request by rhatdan**
--add-host
     --cgroup-parent
     --cpu-period
     --cpu-quota
     --cpu-shares
     --cpuset-cpus
     --cpuset-mems
     --memory
     --memory-swap
     --security-opt
     --ulimit

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
On the plane flight back from Europe, I was adding a bunch of options needed for buildah run and buildah build.  This is how far I got,  If someone would like to take this patch over or break the patch into several smaller patches, that would be welcome.

**Comment by rhatdan** [comment]
I currently commented out support for seccomp, since this will be much more complicated.

**Comment by umohnani8** [comment]
Taking this over.

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 there are a number of trello cards set up for these.  Please grab any that you're going to work on.  I'm on most at the moment, but am not actively working them, I probably should remove myself from them.

Also I'd suggest doing smaller patches and we'll need to also update "podman build".

**Comment by umohnani8** [comment]
@TomSweeneyRedHat yeah, I plan to break this into smaller patches. And will add myself to the trello cards. Thanks for the info :)

**Comment by rhatdan** [comment]
Closing since @umohnani8 has taken it over.

**Pull request closed without merging**
