### PR TITLE
Add unused function param lint check

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Adding check for unused function parameters to the Buildah lint checks.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Failure appears to be a network hiccup.  Will kick the bot.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by nalind** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
