### PR TITLE
Fail if date or git not installed

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces https://github.com/projectatomic/buildah/pull/616

**Comment by rhatdan** [comment]
Should prevent https://github.com/projectatomic/buildah/issues/612 in the future.

**Comment by TomSweeneyRedHat** [comment]
Looks like the tests are breaking, on my vm I'm seeing:  

```
make
go build -ldflags '-X main.gitCommit= aca2a1e -X main.buildInfo=1524575762' -o buildah -tags "   selinux seccomp" ./cmd/buildah
# github.com/projectatomic/buildah/cmd/buildah
usage: link [options] main.o
  -B note
    	add an ELF NT_GNU_BUILD_ID note when using ELF
{lots of info removed}
  -w	disable DWARF generation
make: *** [Makefile:20: buildah] Error 2
```

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  My tests look happier to me.

```
# mv /bin/date /bin/nodate
# make
make: date: Command not found
Makefile:10: *** "date failed".  Stop.
# mv /bin/nodate /bin/date
# mv /usr/bin/git /usr/bin/nogit
# make
make: git: Command not found
Makefile:9: *** "git failed".  Stop.

# mv /usr/bin/nogit /usr/bin/git
# make
{happy make output removed}
```

**Comment by rhatdan** [comment]
@rh-atomic-bot r=TomSweeneyRedHat

**Pull request closed without merging**
