### PR TITLE
Block use of /proc/acpi and /proc/keys from inside containers

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Note this is currently blocked by SELinux.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
