### PR TITLE
Make sure builtin volumes have the correct label

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@ipbabble @nalind @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
Fixes: https://github.com/projectatomic/buildah/issues/338

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Comment by nalind** [comment]
LGTM, but we'll probably need #340 first.

**Comment by nalind** [comment]
A rebase should fix up those test results.

**Comment by rhatdan** [comment]
@rh-atomic-bot r=nalind

**Pull request closed without merging**
