### PR TITLE
Expand variables names for --env

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes https://github.com/projectatomic/buildah/issues/929

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vbatts @TomSweeneyRedHat PTAL

**Comment by vbatts** [comment]
Oh cool. Will try tomorrow. Best to add some tests for this.

**Comment by TomSweeneyRedHat** [comment]
Any doc changes needed?

**Comment by TomSweeneyRedHat** [comment]
Did I mess up the bash commands or am I expecting the wrong behaviour?  With this patch in play:
```
# echo $mygopath
/go

# echo $mypath
/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

# ./buildah config --env 'GOPATH=$mygopath/bin:$mypath' fedora-working-container

# buildah run fedora-working-container /bin/bash

# echo $GOPATH
mygopath/bin:mypath

```
I was expecting 
```
/go/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
```

**Comment by TomSweeneyRedHat** [comment]
I also tried 
```
/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
```
with the same result.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat buildah config has nothing to do with your environment. It takes the environment from inside of the container/image and applies it.

So if you do a podman install image
You will see a couple of environment variables set.

If you config 'GOPATH=$mygopath/bin:$mypath'
Then if the environment variables currently in the container have defined mygopath and mypath, then they will be substituted, otherwise they will not be.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, thanks for the 411 and I dug a little deeper.  I was concerned that we didn't have a way to expand the local envvars and the container's envvars.  But with this fix I think we do.  I might note this in a little blog/tutorial.  The key are the single quotes.  If you use them the variables are expanded from the containers envvars.  No single quotes then the expansion happens locally.  I think this is due to bash and is handy, but we need to doc somewhere.  Testing runs below in case you're interested.

```
# echo $mypath
/home/tsweeney/bin
# echo $mygopath
/home/tsweeney/go
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/notrealpath

# buildah from fedora
fedora-working-container
# buildah run fedora-working-container -- sh -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# buildah run fedora-working-container -- sh -c 'echo $GOPATH'

# ./buildah config --env GOPATH=$mygopath:$mypath fedora-working-container
# buildah run fedora-working-container -- sh -c 'echo $GOPATH'
/home/tsweeney/go:/home/tsweeney/bin

# ./buildah config --env 'GOPATH=$mygopath:$mypath' fedora-working-container
# buildah run fedora-working-container -- sh -c 'echo $GOPATH'
mygopath:mypath

# ./buildah config --env GOPATH=$mygopath:$mypath fedora-working-container
[root@localhost buildah]# buildah run fedora-working-container -- sh -c 'echo $GOPATH'
/home/tsweeney/go:/home/tsweeney/bin

# ./buildah config --env 'GOPATH=$GOPATH:$PATH' fedora-working-container
# buildah run fedora-working-container -- sh -c 'echo $GOPATH'
/home/tsweeney/go:/home/tsweeney/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
```

**Comment by TomSweeneyRedHat** [comment]
LGTM
and again, neat fix and ty for the 411.

**Comment by vbatts** [comment]
Thanks for adding a test for this.
I've just tested with https://gist.github.com/vbatts/4118d3f85b403027892e3be56c3266d2#file-buildah-build-sh and it works as expected!

**Comment by rhatdan** [comment]
@rh-atomic-bot r=vbatts

**Pull request closed without merging**
