### PR TITLE
Handle ErrDuplicateName errors from store.CreateContainer()

### PR DESCRIPTION
**Pull request by nalind**
newBuilder(): When store.CreateContainer() returns a duplicate-name error for a name that we just made up, try again with a different made-up name.

### CODE REVIEW

**Comment by nalind** [comment]
This should fix part of https://github.com/containers/libpod/issues/1146#issuecomment-420428372.

**Comment by TomSweeneyRedHat** [comment]
Does this replace #1005?

**Comment by nalind** [comment]
Oof.  I hadn't realized, but it would.

**Comment by TomSweeneyRedHat** [comment]
Change LGTM and I think I like this approach better then #1005 for the container name.  @steveb WDYT?

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Comment by steveb** [comment]
This fixes #1004 for me, thanks

**Pull request closed without merging**
