### PR TITLE
Switch from using docker to podman for testing in .papr

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Wowsa, all green tests buttons.  LGTM

**Comment by rhatdan** [comment]
@giuseppe @nalind @umohnani8 @baude PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r=giuseppe

**Pull request closed without merging**
