### PR TITLE
Improve buildah push man page and help information

### PR DESCRIPTION
**Pull request by rhatdan**
This better documents the options available to the user.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I am hoping for this update to buildah-push documentation to replace https://github.com/projectatomic/buildah/pull/185

**Comment by nalind** [comment]
LGTM, pending spell-check.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ https://github.com/projectatomic/buildah/pull/186/commits/58976ec3ea7271c0e5a01350ef2db85b2754de19

**Comment by rhatdan** [comment]
@rh-atomic-bot  retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ 58976ec

**Pull request closed without merging**
