### PR TITLE
Test with Go 1.10, too

### PR DESCRIPTION
**Pull request by nalind**
Add Go 1.10.x to our test matrix.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
FWIW, I tried this in #642, and ran into the same errors with the run install.tools.  That's what prompted my PR earlier in the week to get those running outside of Travis, but it didn't seem to help golang 1.10.

```
HEAD is now at c5ec2548 Merge pull request #1527 from mrunalp/spec_bump_v1
ln -sf ../../opencontainers/runc/runc
# github.com/projectatomic/buildah/vendor/github.com/containers/storage/pkg/devicemapper
vendor/github.com/containers/storage/pkg/devicemapper/devmapper_wrapper_deferred_remove.go:12:13: could not determine kind of name for C.dm_task_deferred_remove
# github.com/projectatomic/buildah/vendor/github.com/containers/storage/drivers/btrfs
vendor/github.com/containers/storage/drivers/btrfs/version.go:6:27: fatal error: btrfs/version.h: No such file or directory
 #include <btrfs/version.h>
```

**Comment by nalind** [comment]
bot, retest this please

**Comment by nalind** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
