### PR TITLE
Add golang 1.10 to travis

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Add golang 1.10 to the build mix.  I'm not 100% sure how it will go, so a bit of an experiment.

### CODE REVIEW

**Comment by ripcurld** [comment]
Go 1.10 tests fail when running:
```bash
make install.tools install.libseccomp.sudo all runc validate
          TAGS="apparmor seccomp containers_image_ostree_stub"
```

```shell
# github.com/projectatomic/buildah/vendor/github.com/containers/storage/pkg/devicemapper
vendor/github.com/containers/storage/pkg/devicemapper/devmapper_wrapper_deferred_remove.go:12:13: could not determine kind of name for C.dm_task_deferred_remove
# github.com/projectatomic/buildah/vendor/github.com/containers/storage/drivers/btrfs
vendor/github.com/containers/storage/drivers/btrfs/version.go:6:27: fatal error: btrfs/version.h: No such file or directory
 #include <btrfs/version.h>
                           ^
compilation terminated.
# pkg-config --cflags ostree-1 ostree-1 ostree-1 ostree-1 ostree-1 ostree-1
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
pkg-config: exit status 1
Error: source package github.com/projectatomic/buildah does not pass go vet.
make: *** [validate] Error 1
```
I am not sure whether this is flaky or something was changed in Go `1.10`.

**Comment by TomSweeneyRedHat** [comment]
@nalind took care of this in #711

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Should we close this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan yep, done!

**Pull request closed without merging**
