### PR TITLE
Additional CI tests for buildah bud building from URL

### PR DESCRIPTION
**Pull request by pixdrift**
Signed-off-by: pixdrift <support@pixeldrift.net>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by pixdrift** [comment]
@rhatdan, If you merge #698 I will add some tests for the --label feature to this PR.

**Comment by rhatdan** [comment]
#698 is merged.

**Comment by pixdrift** [comment]
@rhatdan 

Can we merge this before it falls too far behind?

I will put additional tests in another PR.

**Pull request closed without merging**
