### PR TITLE
Fix examples to include context directory

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r

**Comment by rhatdan** [comment]
@rh-atomic-bot -r TomSweeneyRedHat

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
third bot hit is the charm

**Pull request closed without merging**
