### PR TITLE
ci: rename files and use Fedora registry

### PR DESCRIPTION
**Pull request by jlebon**
See commit messages.

### CODE REVIEW

**Comment by rhatdan** [comment]
@jlebon Sign your pull request.

**Comment by jlebon** [comment]
Sign-off added and syntax error fixed! ⬆️

**Comment by jlebon** [comment]
BTW, I was pleasantly surprised to see this repo already made the jump to F26. 👍

**Comment by rhatdan** [comment]
@rh-atomic-bot r+ cce784c

**Pull request closed without merging**
