### PR TITLE
Remove export command

### PR DESCRIPTION
**Pull request by rhatdan**
We have implemented most of this code in kpod export, and we now
have kpod import/load/save.  No reason to implement them in both
commands.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind PTAL

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, and coulda sworn I LGTM'd this yesterday but don't see it.

**Comment by nalind** [comment]
LGTM.
@rh-atomic-bot r+

**Pull request closed without merging**
