### PR TITLE
Show lastest container name in containers cmd

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

With the new rename command the new name of the container was placed at names[0] however in 'buildah containers` we were showing the name from the builder.container field which was the name of the container at it's creation.  This changes that and reworks the structure of the code a bit to make use of a map and slices in both parts of an if statement.

Testing:
```
# buildah from fedora
# buildah rename fedora-working-container my-fedora

Before:
# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
6a26f8bdcc75     *     cc510acfcd70 docker.io/library/fedora:latest  fedora-working-container
# buildah containers --all
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
6a26f8bdcc75     *     cc510acfcd70 docker.io/library/fedora:latest  my-fedora

After:
# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
6a26f8bdcc75     *     cc510acfcd70 docker.io/library/fedora:latest  my-fedora
[root@localhost buildah]# buildah containers --all
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
6a26f8bdcc75     *     cc510acfcd70 docker.io/library/fedora:latest  my-fedora
```

### CODE REVIEW

**Comment by rhatdan** [comment]
@TomSweeneyRedHat You said the old name is still associated with the container?

**Comment by rhatdan** [comment]
I would figure if I rename X->Y, I would be able to recreate a new container named X?

**Comment by q384566678** [comment]
SGTM

**Comment by TomSweeneyRedHat** [comment]
I wasn't sure which way you wanted to go and haven't circled back.  We've the choice of doing it as is in this PR, keeping the original name.  Or we can pretty much chuck all of this and change the name but lose the history.  Is the rename everywhere the approach you'd prefer?

**Comment by rhatdan** [comment]
Yes, We can warn about the loss of history.  But to me Rename means rename.  And this looks more like a tag.
What does Docker rename do?

**Comment by TomSweeneyRedHat** [comment]
Looks like Docker wipes the old name from the container.  I'll back out the change to the containers code then and will change things somewhere in the rename code path to do that.

**Pull request closed without merging**
