### PR TITLE
Add flags validation

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but papr seems to be having deadline issues here as in #876

**Comment by TomSweeneyRedHat** [comment]
FWIW, I don't think there's an issue with this PR, but we probably need an adjustment in paper (Red Hat CI) and/or we need to tweak deadline settings in lint.

**Comment by nalind** [comment]
LGTM
@rh-atomic-bot r+

**Comment by nalind** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by nalind** [comment]
@rh-atomic-bot retry

**Comment by nalind** [comment]
@rh-atomic-bot retry

**Comment by giuseppe** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Pull request closed without merging**
