### PR TITLE
run: fix validate flags

### PR DESCRIPTION
**Pull request by q384566678**
Same like #731.
Found a spelling error, fixed in this pr.

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, retest this please
Thanks @q384566678 LGTM

**Comment by rhatdan** [comment]
@umohnani8 @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
LGTM

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
