### PR TITLE
Small nitpick at matches(Since,Before)Image in cmd/buildah/images

### PR DESCRIPTION
**Pull request by ripcurld0**
Replacing 
```Go
if <condition> {
    return true
}
return false
```
with
```Go
return <condition>
```

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
bot, test pull request

**Comment by TomSweeneyRedHat** [comment]
LGTM.  @ripcurld0 nice eagle eye and thanks for the touch up!

**Comment by ripcurld0** [comment]
my pleasure. 👍

**Comment by rhatdan** [comment]
Thanks @ripcurld0 
@rh-atomic-bot r+

**Comment by nalind** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
@rh-atomic-bot retry

**Comment by rhatdan** [comment]
Homu seems to be stuck, manually merging.

**Pull request merged**
