### PR TITLE
Bump Buildah to v1.1

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

Bump to v1.1

### CODE REVIEW

**Comment by pixdrift** [comment]
@TomSweeneyRedHat, changelog needs update in rpm .spec file
https://github.com/projectatomic/buildah/blob/master/contrib/rpm/buildah.spec
and
https://github.com/projectatomic/buildah/blob/master/CHANGELOG.md

**Comment by TomSweeneyRedHat** [comment]
Hold until the OnBuild #722 gets merged.

**Comment by pixdrift** [comment]
Can I be a pain and ask to block on #684 and #732? Maybe too much self interest? 😏

**Comment by rhatdan** [comment]
#684 does not have a reproducer that we can use to diagnose, so blocking on that would be difficult.
I'm willing to wait on #732.

**Comment by pixdrift** [comment]
@rhatdan, I provided a complete reproducer for #684, third comment from the bottom.

**Comment by TomSweeneyRedHat** [comment]
I've updated with today's commits, but I think we should still hold on this @rhatdan.  Let's touch base Friday.

**Comment by TomSweeneyRedHat** [comment]
Looks like a test system flake.  Going to rekick the tests.

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by rhatdan** [comment]
Replaced by https://github.com/projectatomic/buildah/pull/769

**Comment by pixdrift** [comment]
Still blocked by #684?

**Comment by rhatdan** [comment]
@pixdrift No we are releasing.  We will release again when #684 is fixed, as well as when we get the --layers (caching) support.

**Pull request closed without merging**
