### PR TITLE
DO NOT MERGE TEST ONLY MODIFIES VENDOR: Ignore EmptyLayer layers on storage input

### PR DESCRIPTION
**Pull request by mtrmac**
TESTING ONLY this approach for fixing #684.

### CODE REVIEW

**Comment by mtrmac** [comment]
Note to self: This may break existing installations - if the top layers are `EmptyLayer`, the topmost layer for an image will now be a the topmost non-empty one, and the code expects images with the same config to have the same topmost layer.  I.e. `pull foo; update c/image; pull foo` could break.

**Comment by mtrmac** [comment]
@nalind RFC.  Instead of expecting `EmptyLayer` layers to exist, expect them not to exist, and modify c/image/storage to ignore them when pulling images.

This is pretty much the opposite to the attempt in #762 (which expected `EmptyLayer` to exist, as they do in v2s1, but they don’t exist at all in v2s2/OCI).

See also https://github.com/projectatomic/buildah/pull/775#issuecomment-396321518 , the
```go
		if img.TopLayer != lastLayer {
			logrus.Debugf("error creating image: image with ID %q exists, but uses different layers", intendedID)
			return errors.Wrapf(storage.ErrDuplicateID, "image with ID %q already exists, but uses a different top layer", intendedID)
		}
```
check could be broken.  We could just remove it, or maybe compute both the top non-empty and top possibly-empty layer, and allow reusing images with either.

**Comment by mtrmac** [comment]
This is known to be insufficient for @pixdrift ’s reproducer from #684 , see #776 for the extra needed fix.

**Comment by rhatdan** [comment]
@mtrmac Since https://github.com/projectatomic/buildah/pull/776 has merged, can this move forward?

**Comment by mtrmac** [comment]
> @mtrmac Since #776 has merged, can this move forward?

It’s very likely this breaks corner cases (pulling the same image after upgrade, because the top layer ID changes; pulling v2s1 and pushing it out again, because the intermediate “throwaway” layers are not stored), I am still looking into that.

I’d also _very much_ appreciate a review by someone who understands c/storage and knows the context I don’t know I don’t know.

**Comment by rhatdan** [comment]
@nalind we need you to review this. ASAP

**Comment by TomSweeneyRedHat** [comment]
I might be off base, but thought this PR was not going to be merged.  Rather @mtrmac was going to open one in containers/image and then Buildah would have to vendor that in.  The changes s/b the same though, so a review would be good regardless.

**Comment by mtrmac** [comment]
> I might be off base, but thought this PR was not going to be merged. Rather @mtrmac was going to open one in containers/image and then Buildah would have to vendor that in.

Good point, yes, that’s the very likely outcome. But right now I don’t have a comprehensive c/image PR, so this is the only place I where can currently ask for a review of the core idea.

**Comment by mtrmac** [comment]
Please see https://github.com/containers/image/pull/472 for what could be a comprehensive fix. This PR now only vendors that branch to run `buildah` tests.

**NOTE**: That PR punts on handling pre-existing v2s1 images; users may have to delete/untag them and re-pull using the fixed code. Because comprehensively supporting the old representation would be a fair amount of complex code (and mean a commitment to add such support to any future layer-walking code), and because quite a few uses of v2s1 haven’t worked correctly anyway, on balance it seems to me that giving up is the better long-term choice.  OTOH possible deployments that only run containers (k8s nodes?), and are configured to re-pull the same image again for some reason, may be affected; please speak up in https://github.com/containers/image/pull/472 if this is not acceptable.

**Comment by mtrmac** [comment]
#860 is equivalent, closing this one to simplify the PR list.

**Pull request closed without merging**
