### PR TITLE
Vendor in latest container/storage for devicemapper support

### PR DESCRIPTION
**Pull request by rhatdan**
container/storage now supports devicemapper options that allow you to
configure it.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by TomSweeneyRedHat** [comment]
Change LGTM, but issues in tests here too:

```
# time="2018-05-19T10:30:20Z" level=debug msg="GET https://registry.access.redhat.com/v2/alpine/manifests/latest"
# time="2018-05-19T10:30:21Z" level=debug msg="error pulling image \"registry.access.redhat.com/alpine\": Error determining manifest MIME type for docker://registry.access.redhat.com/alpine:latest: Error reading manifest latest in registry.access.redhat.com/alpine: unknown: Not Found"
# time="2018-05-19T10:30:21Z" level=debug msg="error pulling and reading image \"registry.access.redhat.com/alpine\": Error determining manifest MIME type for docker://registry.access.redhat.com/alpine:latest: Error reading manifest latest in registry.access.redhat.com/alpine: unknown: Not Found"
# time="2018-05-19T10:30:21Z" level=error msg="Error determining manifest MIME type for docker://registry.access.redhat.com/alpine:latest: Error reading manifest latest in registry.access.redhat.com/alpine: unknown: Not Found"
ok 86 from cpuset-mems test

```

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
If you run these tests in a container without specifying a driver, all drivers are tested.  When devicemapper is tried, it does not specify a device, (Loopback is no longer supported) and that causes the failure.

@nalind Is there a way to drop devicemapper when the user does not specify a driver?
graphdriver="", don't use devicemapper?

**Comment by nalind** [comment]
@rhatdan To take `devicemapper` out of the list of drivers that we attempt to use when none is specified and there isn't evidence that one was previously used for that particular storage root, removing it from the `priority` list in `drivers/driver_linux.go` should work.

**Comment by rhatdan** [comment]
@nalind would you prefer that?

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @umohnani8 PTAL
I think this is ready to merge.

**Comment by umohnani8** [comment]
LGTM

**Pull request closed without merging**
