### PR TITLE
Update 01-intro.md

### PR DESCRIPTION
**Pull request by KyleRConway**
Adding command to explicitly become root user. I was trying to run commands with "sudo" in front and thus had issues following guide (new user) and this would have helped!

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, add author to whitelist
```
@KyleRConway Thanks for the PR, but you have to sign it.
git commit -a --ammend -s
git push --force
```
Should fix it.

**Comment by KyleRConway** [comment]
Thanks, @rhatdan & @TomSweeneyRedHat 
I made the edit through github's web-GUI while working through the guide, so I'll work on signing the PR when at my machine later tonight. Appreciate the help!

**Comment by KyleRConway** [comment]
@rhatdan -- Hopefully this was successful. Let me know if not. Appreciate the help.

**Comment by rhatdan** [comment]
Looks good.  Some problems with the test infrastructure.  
@rh-atomic-bot r+

**Pull request closed without merging**
