### PR TITLE
New, non-underware hat logo artwork (replaces 357)

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Submitting for @mairin #357 to get past signature issues.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
I'd hope to just update #357, but couldn't figure out the git magic.  This one too has my prior touchups to the scripts.

**Comment by rhatdan** [comment]
LGTM
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
Git is still looking for a signature on @mairin 's original commit in his commit.  Trying to figure out how to make it happy without luck so far.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by nalind** [comment]
FWIW, starting a `git rebase -i`, and then specifying the `reword` command instead of the default `pick` for the unsigned commits, would offer an opportunity to manually edit the commit messages.

**Pull request closed without merging**
