### PR TITLE
Explain Open Container Initiative (OCI) acronym, add link

### PR DESCRIPTION
**Pull request by ElijahLynn**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, add author to whitelist

**Comment by TomSweeneyRedHat** [comment]
@ElijahLynn thanks for the contribution!  I don't think you signed your commit and the test will likely fail due to that.  You'll need to 'git commit --amend -s" and then repush.
Nice catch btb, I would sworn we'd a link on the page, but it must of inadvertently been removed at some point.  So thanks!

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by ElijahLynn** [comment]
Looks like the web-UI signed the commit for me even though I didn't have a GPG/PGP key when I created it (I do now but it is a different key).
image

Is the failure because of the signing? I looked briefly in the Red Hat CI test https://s3.amazonaws.com/aos-ci/ghprb/projectatomic/buildah/1c1d5d9c98e32648fbe7482b744aca287ac1de46.0.1534540261773368490/output.log but couldn't tell.

**Comment by TomSweeneyRedHat** [comment]
Hi @ElijahLynn,

Yep, the tests are failing due to the PR not being signed.  I find it easier to spot in Travis and it shows:

```
HEAD is now at 2c632d1a Merge pull request #1824 from cyphar/fix-mips-build-devNumber
ln -sf ../../opencontainers/runc/runc
 1c1d5d9 - FAIL - does not have a valid DCO
1 commits to fix
make: *** [validate] Error 1
```

**Comment by ElijahLynn** [comment]
done

**Comment by ripcurld** [comment]
@ElijahLynn - `verified signature` has nothing to do with `signed-off`. 
The CI bot needs to see "Signed-off-by: Elijah Lynn <youremailhere>" in your commit body.

Make sure you set name and email in your `git config`:

```
git config user.name
git config user.email
```

If you don't see anything in the output set it:

```
git config --global user.name "Your Full Name"
git config --global user.name "your@email.com"
```

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by rhatdan** [comment]
We should be able to handle this, when someone corrects stuff via github, without forcing them to create a PR via git command line tool.

**Comment by ElijahLynn** [comment]
Thanks all, had no idea signed off and signed commits were different.

**Comment by ElijahLynn** [comment]
Related PR to better expose "Sign your PRs" in contributing.md TOC, https://github.com/projectatomic/buildah/pull/954. Will admit I did _not_ read contributing.md before this PR though, so it isn't like I missed it.

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by TomSweeneyRedHat** [comment]
@ElijahLynn thanks for sticking with this and pushing through o this PR.

**Pull request closed without merging**
