### PR TITLE
Small cleanup on buildah rmi to make code cleaner

### PR DESCRIPTION
**Pull request by rhatdan**
While adding rmi to ocid, I was asked to make this change, so want
to keep the code in buildah and ocid for these functions as close as
possible to the same.

### CODE REVIEW

**Comment by nalind** [comment]
Missing "Signed-off By" (can be fixed with "git commit --amend -s" and re-pushing your branch), otherwise LGTM.

**Comment by TomSweeneyRedHat** [comment]
changes LGTM

**Comment by rhatdan** [comment]
@nalind now signed.

**Comment by nalind** [comment]
@rh-atomic-bot r+ a076d514dd5897214768a227df7c43ad1f2f75be

**Pull request closed without merging**
