### PR TITLE
Vendor updates

### PR DESCRIPTION
**Pull request by nalind**
Update our vendored dependencies.

### CODE REVIEW

**Comment by nalind** [comment]
Note that the new `containers/storage` moves the default locations, per https://github.com/containers/storage/pull/31.

**Comment by rhatdan** [comment]
Looks like tests are failing.

Otherwise LGTM

**Comment by nalind** [comment]
For whatever reason, this needs #24, when tests were passing without it earlier.

**Comment by nalind** [comment]
Rebasing.

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
Thanks, merging.

**Comment by nalind** [comment]
[[Buildah] build-dockerfile](https://trello.com/c/AyBXqoRY/443-buildah-build-dockerfile)

**Pull request merged**
