### PR TITLE
Minor fix for lighttpd example script in README

### LINKED ISSUE #579: README: invalid command to write lighttpd.sh
**Description**

The shell command with the "here document" (`cat > lighttpd.sh <<EOF`) does not work because it includes back ticks that are executed in place rather then being inserted as in in the `lighttpd.sh` file.

**Steps to reproduce the issue:**
1. Copy paste the lines from the README in a terminal

**Describe the results you received:**
```
$ cat > lighttpd.sh <<EOF
> #!/bin/bash -x
> 
> ctr1=`buildah from ${1:-fedora}`
> 
> ## Get all updates and install our minimal httpd server
> buildah run $ctr1 -- dnf update -y
> buildah run $ctr1 -- dnf install -y lighttpd
> 
> ## Include some buildtime annotations
> buildah config --annotation "com.example.build.host=$(uname -n)" $ctr1
> 
> ## Run our server and expose the port
> buildah config $ctr1 --cmd "/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf"
> buildah config $ctr1 --port 80
> 
> ## Commit this container to an image name
> buildah commit $ctr1 ${2:-$USER/lighttpd}
> EOF
mkdir /var/lib/containers/storage: permission denied
mkdir /var/lib/containers/storage: permission denied
$ grep ^ctr1 lighttpd.sh 
ctr1=
$
```
**Describe the results you expected:**

The command `buildah from ${1:-fedora}` should be inserted in `lighttpd.sh` rather than trying to execute it (and failing because I'm not root).

### PR DESCRIPTION
**Pull request by pixdrift**
Fixes #579 

Signed-off-by: pixdrift <support@pixeldrift.net>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
bot, retest this please.

**Comment by TomSweeneyRedHat** [comment]
Bot is ignoring me, going to close and reopen this to force the tests.

**Comment by TomSweeneyRedHat** [comment]
retest

**Comment by rhatdan** [comment]
bot, retest this please

**Comment by pixdrift** [comment]
Can we get CI re-run again? I will follow up closing the issue after the merge.

**Comment by ripcurld** [comment]
bot, retest this please.

**Comment by rhatdan** [comment]
@pixdrift Could you close the PR and reopen to see if it will retest, or you could

git commit -a --amend -s
Save it
git push --force

And it should retrigger. Not sure why the bot will not retest.

**Comment by pixdrift** [comment]
@rhatdan, no drama. Will sort it out in the morning.

**Pull request closed without merging**
